_target_: src.models.cmu_mosei_module.CmuMoseiModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0


model:
  _target_: src.models.components.bert_emotion_classifier.BERTEmotionClassifier
  num_labels: 7
  dropout_value: 0.3

# compile model for faster training with pytorch 2.0
compile: false
