_target_: src.models.cmu_mosei_module.CmuMoseiModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0


model:
  _target_: src.models.components.emotion_embedding_creator.EmotionClassifier
  embedding_creator:
    _target_: src.models.components.glove_embedding_creator.GloveEmotionEmbeddingCreator
    embedding_dim: 300
    kernel_sizes: [3, 4, 5]
    num_filters: 50
  classifier:
    _target_: src.models.components.classifier.Classifier
    input_size: 150
    dropout_value: 0.3
    hidden_size: 16

# compile model for faster training with pytorch 2.0
compile: false
